name: Django CI

on:
  push:
  pull_request:

jobs:
  build:
    name: Build application
    runs-on: self-hosted
    strategy:
      matrix:
        python-version: [3.13]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Save dependencies for next jobs
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

  lint:
    name: Run linters
    runs-on: self-hosted
    needs: build

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v3
        with:
          python-version: 3.13
      - name: Restore cached dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
      - run: pip install -r requirements.txt black flake8
      - name: Run linters
        run: |
          black --check .
          flake8 .

  test:
    name: Run tests
    runs-on: self-hosted
    needs: lint

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v3
        with:
          python-version: 3.13
      - name: Restore cached dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
      - run: pip install -r requirements.txt
      - name: Run tests
        run: |
          python manage.py test
