name: Django CI

on:
  push:
  pull_request:

jobs:
  build:
    name: Build application

    runs-on: self-hosted
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ 3.12, 3.13 ]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install Linters
        run: pip install black flake8


  lint:
    name: Run linters
    runs-on: self-hosted

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          black: true
          flake8: true

  test:
    name: Run tests
    runs-on: self-hosted

    steps:
      - name: Run tests
        run: |
          python manage.py test